import type { Metadata } from "next"
import { Inter } from "next/font/google"
import React, { Suspense } from "react"
import LoginLoading from "@/app/login/loading"
import ProblemLoading from "@/app/problems/loading"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function ProblemsLayout({
                                      children,
                                    }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <section>
      <Suspense fallback={<ProblemLoading/>}>
        {children}
      </Suspense>
    </section>
  )
}
