import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import SiteFooter from "@/components/footer"
import { SiteHeader } from "@/components/header"
import React, { Suspense } from "react"
import HomeLoading from "@/app/loading"
import { StateProvider } from "@/components/context-api/logged-state"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <StateProvider>
            <SiteHeader/>
            <Suspense fallback={<HomeLoading/>}>
              {children}
            </Suspense>
            <SiteFooter />
          </StateProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
