import type { Metadata } from "next"
import { Inter } from "next/font/google"
import React, { Suspense } from "react"
import LoginLoading from "@/app/login/loading"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function LoginLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <section>
      <Suspense fallback={<LoginLoading/>}>
        {children}
      </Suspense>
    </section>
  )
}
