import type { Metadata } from "next"
import { Inter } from "next/font/google"
import React, { Suspense } from "react"
import SignupLoading from "@/app/signup/loading"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function SignupLayout({
                                         children,
                                       }: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <section>
      <Suspense fallback={<SignupLoading/>}>
        {children}
      </Suspense>
    </section>
  )
}
